# Generated by Django 4.0 on 2022-10-23 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким адресом электронной почты уже существует.'}, help_text='Обязательное поле. Только буквы, цифры и следующие символы: @/./+/-/_.', max_length=150, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Адрес электронной почты'),
        ),
    ]
