# Generated by Django 4.0 on 2022-11-07 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
