version: "3.10"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-kwg*lke9arp@#vs0@6fr+9lo_!(v@(4+efc)gh!ils&y*(j_@(
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    ports:
      - "6379:6379"
  celery:
    build: .
    entrypoint: celery
    command: -A pizza.celery worker --loglevel=info
    volumes:
      - .:/usr/src/app/
    links:
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-kwg*lke9arp@#vs0@6fr+9lo_!(v@(4+efc)gh!ils&y*(j_@(
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - redis
      - db
  celery-beat:
    build: .
    entrypoint: celery
    command: -A pizza.celery beat --loglevel=info
    volumes:
      - .:/usr/src/app/
    links:
      - celery
      - redis
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-kwg*lke9arp@#vs0@6fr+9lo_!(v@(4+efc)gh!ils&y*(j_@(
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - celery
      - redis
      - db