# Generated by Django 4.0 on 2022-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Наименование отчёта'),
        ),
        migrations.AlterField(
            model_name='report',
            name='remarks',
            field=models.TextField(verbose_name='Текст отчёта'),
        ),
    ]
