# Generated by Django 4.0 on 2022-10-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_salesman_alter_position_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('В процессе выполнения', 'В процессе выполнения'), ('Завершён', 'Завершён'), ('Отменён', 'Отменён')], default='В процессе выполнения', max_length=25),
        ),
    ]
