# Generated by Django 4.0 on 2022-10-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_category_alter_productreview_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Пицца', 'Пицца'), ('Напитки и закуски', 'Напитки и закуски')], default='Пицца', max_length=50),
        ),
    ]
